name: Outdated package checks

permissions:
  contents: read
  pull-requests: write

# Run workflow on pull request to the main branch
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.github/**'
      - 'LICENSE'
      - 'powershell/**'
  
  workflow_dispatch:

jobs:
  outdated-packages-check:
    runs-on: ubuntu-latest

    steps:
      - uses: trossr32/outdated-packages-action@v1.7.0
        with:
          use-npm-outdated: true